# Generated by Django 5.0.3 on 2024-03-19 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="description",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="dish",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="description",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
