# Generated by Django 5.0.3 on 2024-03-20 15:12

import django.core.validators
import menu.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_alter_dish_description_alter_dish_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="image",
            field=models.FileField(
                null=True, upload_to=menu.models.dish_image_file_path
            ),
        ),
        migrations.AlterField(
            model_name="dish",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
