# Generated by Django 5.0.3 on 2024-03-21 10:40

import menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_dish_image_alter_dish_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="image",
            field=models.ImageField(
                null=True, upload_to=menu.models.dish_image_file_path
            ),
        ),
    ]
