# Generated by Django 5.0.3 on 2024-03-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_alter_dish_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="added_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="dish",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
