# Generated by Django 5.0.3 on 2024-03-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0005_alter_dish_added_on_alter_dish_updated_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="added_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="menu",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
